[Settings]
# The Application ID from your Discord Developer Portal
ClientID=1400667687020920914

# The name of the asset uploaded in your Discord Art Assets
LargeImageKey=aksara_logo

# The text displayed when hovering over the large image
LargeImageText=Aksara Roleplay

# The name of the small icon asset (e.g., samp or status icon)
SmallImageKey=samp

# The text displayed when hovering over the small image
SmallImageText=Samp Icon


# --- INTERACTIVE BUTTONS ---

# LABEL: The text displayed on the button
# URL: The link destination (MUST start with http:// or https://)
# Note: Leave the label blank to disable the button.

# Button 1 Settings
ButtonLabel1=Join Discord
DiscordURL1=https://discord.gg/bmDMA5zbQV

# Button 2 Settings
ButtonLabel2=Website
DiscordURL2=https://aksara-rp.com


# --- SERVER FILTERING ---

# EnableFilter: Set to 1 to only show RPC on specific servers. Set to 0 to show on ALL servers.
EnableFilter=0

# FilterName: The keyword that must be present in the Server Hostname (Case-insensitive)
FilterName=aksara
