[Settings]
# Client ID of your discord bot
ClientID=1400667687020920914

LargeImageKey=aksara_logo
LargeImageText=Aksara Roleplay
SmallImageKey=samp
SmallImageText=Samp Icon

# Button 1 (Leave blank if you don't want to use it)
ButtonLabel1=Join Discord
DiscordURL1=https://discord.gg/bmDMA5zbQV

# Button 2 (Leave blank if you don't want to use it)
ButtonLabel2=Website
DiscordURL2=https://aksara-rp.com

# Server Filter (EnableFilter: 1 = Enabled, 0 = Disabled)
EnableFilter=0
FilterName=aksara