[Settings]
# Client ID dari bot discord kamu
ClientID=1400667687020920914

LargeImageKey=aksara_logo
LargeImageText=Aksara Roleplay
SmallImageKey=samp
SmallImageText=Samp Icon

# Tombol 1 (Kosongkan jika tidak ingin digunakan)
ButtonLabel1=Join Discord
DiscordURL1=https://discord.gg/bmDMA5zbQV

# Tombol 2 (Kosongkan jika tidak ingin digunakan)
ButtonLabel2=Website
DiscordURL2=https://aksara-rp.com

# Filter Server (EnableFilter: 1 = Aktif, 0 = Nonaktif)
EnableFilter=1
FilterName=aksara